apiVersion: v1
kind: Service
metadata:
  name: vocdoni-node-service
  labels:
    app: vocdoni-node
spec:
  selector:
    vocdoni: node
  ports:
  - name: vocdoni-port
    port: 9090
    targetPort: 9090
  - name: cometbft1
    port: 26656
    targetPort: 26656
  - name: cometbft2
    port: 26657
    targetPort: 26657
  - name: cometbft3
    port: 26658
    targetPort: 26658
  type: LoadBalancer

